### ISSUE TITLE
Problem pri spousteni spring-core ERROR:  No qualifying bean of type 'org.example.SpellChecker'

### ISSUE THREAD

**Issue by LucyQuantAnalyst** [GeorgeQuantAnalyst/spring-examples#1]
Prosim o provereni proc mi to dava tuto chybu pri spusteni aplikace spring-core

```log
/home/osboxes/.jdks/corretto-17.0.8/bin/java -javaagent:/snap/intellij-idea-community/451/lib/idea_rt.jar=33367:/snap/intellij-idea-community/451/bin -Dfile.encoding=UTF-8 -classpath /home/osboxes/SourceCode/spring-examples/spring-core/target/classes:/home/osboxes/.m2/repository/org/springframework/spring-context/6.0.11/spring-context-6.0.11.jar:/home/osboxes/.m2/repository/org/springframework/spring-aop/6.0.11/spring-aop-6.0.11.jar:/home/osboxes/.m2/repository/org/springframework/spring-beans/6.0.11/spring-beans-6.0.11.jar:/home/osboxes/.m2/repository/org/springframework/spring-core/6.0.11/spring-core-6.0.11.jar:/home/osboxes/.m2/repository/org/springframework/spring-jcl/6.0.11/spring-jcl-6.0.11.jar:/home/osboxes/.m2/repository/org/springframework/spring-expression/6.0.11/spring-expression-6.0.11.jar:/home/osboxes/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar org.example.EmailApplication
Aug 22, 2023 2:32:20 PM org.springframework.context.support.AbstractApplicationContext refresh
WARNING: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'emailClient': Unsatisfied dependency expressed through field 'spellChecker': No qualifying bean of type 'org.example.SpellChecker' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier("advancedSpellChecker")}
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'emailClient': Unsatisfied dependency expressed through field 'spellChecker': No qualifying bean of type 'org.example.SpellChecker' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier("advancedSpellChecker")}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:716)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:696)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:93)
	at org.example.EmailApplication.main(EmailApplication.java:8)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.example.SpellChecker' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier("advancedSpellChecker")}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1824)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1383)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713)
	... 15 more
```

**Comment by GeorgeQuantAnalyst** [comment]
# Analyza

Problem s vytvarenim beany "emailClient" v kontejneru IoC ve Springu, pri inicializaci se nepodarilo najit beanu "advancedSpellChecker".

## Chyba
```log
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'emailClient': Unsatisfied dependency expressed through field 'spellChecker': No qualifying bean of type 'org.example.SpellChecker' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier("advancedSpellChecker")}
```

## Mozne priciny
1. **Neexistující bean s požadovaným typem**: Chyba může být způsobena tím, že Spring nemá žádnou definici beanu s požadovaným typem (`SpellChecker`). Tím pádem nemá Spring žádnou beanu, kterou by mohl použít pro injektování do `spellChecker` závislosti.

2. **Nesprávně definovaná bean**: Pokud máte definovánu beanu pro `SpellChecker`, může být chyba v její konfiguraci. Například může chybět anotace `@Component`, `@Service` nebo `@Bean`, která označuje tuto třídu jako Spring beanu.

3. **Více bean s rovnakým typem**: Pokud máte více bean s typem `SpellChecker`, může dojít k nejednoznačnosti při injektování. V tomto případě by měl být použit kvalifikátor (`@Qualifier`) k určení, kterou konkrétní beanu chcete použít.

4. **Konflikty v balíčcích**: Pokud máte třídy ve více balíčcích a neprovádíte správně komponentovou skenování (`@ComponentScan`), může Spring mít problém s nalezením beanu.

5. **Chyby v konfiguraci**: Chyby v konfiguračních souborech (např. `application.properties` nebo `application.yml`) mohou vést k tomu, že Spring nenačte správně definované bean.


Vetev: [feature/spring_core_example_lucka](https://github.com/GeorgeQuantAnalyst/spring-examples/tree/feature/spring_core_example_lucka)

**Comment by GeorgeQuantAnalyst** [comment]
# Reseni

Oprava inicializace beany "emailClient"

**Commit message**
```
Fixed inject bean spellChecker
- BasicSpellChecker and AdvancedSpellChecker implement interface SpellChecker
- bean create method should return general SpellChecker type instead concrete
- Inject bean "advancedSpellChecker" into bean "emailClient" via constructor
```

Commit: [ed1b4b0ae088d277bdb8bb917b111e010931dbdb](https://github.com/GeorgeQuantAnalyst/spring-examples/commit/ed1b4b0ae088d277bdb8bb917b111e010931dbdb)
